export enum Tag {
    BUILDING = 'building',
    SPACE = 'space',
    SCIENCE = 'science',
    POWER = 'power',
    EARTH = 'earth',
    JOVIAN = 'jovian',
    VENUS = 'venus',
    PLANT = 'plant',
    MICROBE = 'microbe',
    ANIMAL = 'animal',
    CITY = 'city',
    MOON = 'moon',
    MARS = 'mars',
    CRIME = 'crime',
    WILD = 'wild',
    EVENT = 'event',
    CLONE = 'clone',
    /** MutationMarkets: added by any Infection, never printed on a card and never chosen by Tag Diversifier. */
    INFECTED = 'infected',
}

export const ALL_TAGS = [
  Tag.BUILDING,
  Tag.SPACE,
  Tag.SCIENCE,
  Tag.POWER,
  Tag.EARTH,
  Tag.JOVIAN,
  Tag.VENUS,
  Tag.MOON,
  Tag.MARS,
  Tag.PLANT,
  Tag.MICROBE,
  Tag.ANIMAL,
  Tag.CRIME,
  Tag.CITY,
  Tag.WILD,
  Tag.EVENT,
  Tag.CLONE,
  Tag.INFECTED,
] as const;
